### PR TITLE
2.0 Release

### PR DESCRIPTION
**Pull request by BenLorantfy**

### CODE REVIEW

**Review by jwinn — APPROVED** [review]
Read through the changes and LGTM-haven't had availability to actually run and test locally, but please feel free to merge. 👍

**Review by julienben — APPROVED** [review]
LGTM!!

**Comment by julienben** [comment]
Maybe consider adding instructions for upgrading if they're necessary in any way?

**Comment by Scott-HangarA** [comment]
Hi just curious what the status is on this

**Comment by joejordan** [comment]
Are there any additional holds in getting this merged? Tried running `npm install https://github.com/react-boilerplate/redux-injectors#dev` to get a jump on the improvements but it didn't appear to be fully baked, as it was unable to resolve the package.

**Comment by BenLorantfy** [comment]
@joejordan @Scott-HangarA I'm doing some more testing before releasing this.  You can install version `2.0.0-rc` in the meantime.

**Comment by mawi12345** [comment]
@BenLorantfy Can you please publish an rc the includes #29.

**Comment by bbaaxx** [comment]
Hi, can I help complete this merge ? What is required?

**Comment by Clorr** [comment]
@bbaaxx Seems the master has 1 new commit, so dev is 1 commit behind. Also, there is a branch with some versions bumping, but I don't know the status of all of this. It seems so close from being ready, but yet it is stall...

**Pull request merged**
