### PR TITLE
Add logo and build badge

### PR DESCRIPTION
**Pull request by BenLorantfy**
- Adds logo and build badge (see https://github.com/react-boilerplate/redux-injectors/pull/9/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
- Plan is to change URL to point to master branch instead of blob once logo is in master.
  - Tried using relative link in https://github.com/react-boilerplate/redux-injectors/pull/9/commits/4f15f4088c90cded6413f40fe64d7b9eebfba1f6 but I can't do an image width with relative links, so the logo just expands to the width of the README and looks too big on desktop

### CODE REVIEW

**Comment by BenLorantfy** [comment]
Here's a few options:
Screen Shot 2019-11-27 at 9 44 03 AM

I think I prefer the 2nd one

**Comment by julienben** [comment]
The first one didn't look like this for me. It looked like this:
image
So there's a font problem + the space before the dash.

But yeah I agree that the second one is nicer. Maybe upload a PNG instead of an SVG if it works better. Or rasterize the font in the SVG?

**Comment by BenLorantfy** [comment]
Oh weird, I guess your system doesn't have 'Lato Black'. I'll try changing the font to a shape.

**Comment by BenLorantfy** [comment]
Ok there, does it have the correct font for you now?

**Comment by julienben** [comment]
I think so. This is what I see now:

image

**Comment by BenLorantfy** [comment]
ok cool. Can you approve one more time? 🙂

**Pull request merged**
