### PR TITLE
Fix react warning about causing a render during a render

### PR DESCRIPTION
**Pull request by BenLorantfy**
## This PR does a few things:

- Changes hooks to use useLayoutEffect instead of injecting during the render.  This fixes the warning but comes with its own tradeoffs.  For example, if an action is dispatched inside a useLayoutEffect inside a child component, it will be dispatched before the reducers/sagas have been injected.
- Changes hooks to return booleans indicating whether or not the injection has completed. These can be used to mitigate the tradeoffs explained above.  Components can check if the reducer/saga has been injected before rendering their children.
- Adds a warning to the README recommending `shouldHotReload` be set to false inside the redux-devtools options.  This is because otherwise redux-devtools will re-dispatch previous actions when a reducer is injected.
- Updates the docs in a few other spots explaining these changes
- Bumps the major version, as this could break apps that dispatch actions inside useLayoutEffect
- Adds an `example` directory

### New Feature
- This PR also adds a `createManager` factory.  Usage:

```
const BooksManager = createManager({ key: "books", name: "BooksManager", reducer: booksReducer, saga: booksSaga });

<BooksManager>
  <SomeOtherComponent />
</BooksManager>
```

The books manager will only render its children after the reducer and saga have been injected.

See [this comment](https://github.com/react-boilerplate/redux-injectors/issues/19#issuecomment-664034380) for more details
Closes https://github.com/react-boilerplate/redux-injectors/issues/19

### CODE REVIEW

**Comment by danielrob** [comment]
Question: 
Would using `useSelector` straight after `useInjectReducer` in the same component in this PR still work? E.g.
```
useInjectReducer("injectedDomain", reducer); 
const xyz = useSelector(state => state.injectedDomain.xyz);
```

I'm not sure how late useLayoutEffect is deferring the domain injection?

**Comment by BenLorantfy** [comment]
That should still work but I'll add a test for it

**Comment by danielrob** [comment]
If not I think this lib is headed towards a choice between HOC or DIY wrapper using hooks api, or as you said, a factory to create your wrapper too. But a pure hooks approach just seems dead in the water unless one is willing to accept all the caveats.

**Comment by julienben** [comment]
I agree with @danielrob. In my team we didn't want to deal with the caveats so we switched to using the HOC only. We created our own HOC which handles both reducer and saga injection.

I'm still happy to review this PR if you'd like to merge and release it but it does have an additional caveat that needs to be handled: The `isInjected` mechanism doesn't take into account the different saga injection modes.

**Comment by dathacky** [comment]
Niceeee

**Review by jwinn — APPROVED** [review]
LGTM 👍 I don't have the ability to test locally right now, but this looks good.

**Comment by BenLorantfy** [comment]
@julienben Do you want to review this before I merge it?  I've removed the `mode` parameter from `useInjectSaga` (it now uses the `COUNT` mode which was introduced in this PR #24 ) as well as add a new API called `createManager`.  I also added an example app.

image

**Comment by BenLorantfy** [comment]
@julienben I merged but feel free to still review if you find some time

**Comment by BenLorantfy** [comment]
@julienben I merged but feel free to still review if you find some time

**Pull request merged**
