### PR TITLE
More inclusive peer dependencies

### LINKED ISSUE #26: update to react 17
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0" from redux-injectors@1.3.0
npm ERR! node_modules/redux-injectors
npm ERR!   redux-injectors@"*" from the root project

had to do this.. also react-boilerplate-cra still on version 16
```npm i redux-injectors --force```

### PR DESCRIPTION
**Pull request by BenLorantfy**
Closes #26

### CODE REVIEW

**Comment by RayanD-W** [comment]
Up please

**Review by RayanD-W — APPROVED** [review]

**Comment by Ceezik** [comment]
Pls accept

**Review by Ceezik — APPROVED** [review]

**Comment by Fabazad** [comment]
up

**Review by payouri — APPROVED** [review]
No breaking changes involved

**Review by Fabazad — APPROVED** [review]

**Review by klewar2 — APPROVED** [review]
Approved

**Comment by BenLorantfy** [comment]
I appreciate the approval guys but I need an approval from a collaborator to merge lol

**Comment by BenLorantfy** [comment]
@jwinn or @julienben do you have a sec to look at this?

**Review by iisdan — APPROVED** [review]

**Review by jwinn — APPROVED** [review]

**Pull request merged**
