### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by BenLorantfy**

### CODE REVIEW

**Comment by BenLorantfy** [comment]
I wonder if we should do a merge commit instead of squash merge dev -> master? Just so we maintain the history?

**Comment by julienben** [comment]
Yes, we can do that. (Not that we would truly lose the commit history. The `dev` branch is sticking around ;)

Also, this is your 1.0 release. It needs a [release](https://github.com/react-boilerplate/redux-injectors/releases) to go with it.

**Comment by julienben** [comment]
I believe it goes in this order:
- Merge dev into master
- Create a release
- Publish to npm

Maybe take a look at an article like [this](https://codeburst.io/how-to-create-and-publish-your-first-node-js-module-444e7585b738) to make sure we covered everything?

(Also, I enabled merge commits. Let's try to remember to use them only for merging dev into master.)

**Comment by BenLorantfy** [comment]
Ok, sounds good. If you can approve this I can merge and create the release.

**Pull request merged**
